### ISSUE TITLE
Voting chart for 2022-12-05 incorrectly lists votes for CC-1 and MC-2

### ISSUE THREAD

**Issue by NelsonPJ** [a2council/a2council.vote#41]
The voting chart for 2022-12-05 lists items CC-1 and MC-2 each as having passed with 11 votes. These items were not voted on at the Council meeting.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/11741450/205965603-44abee31-0bfa-41f7-8b1a-248ab7f22a99.png">

**Comment by bdimcheff** [comment]
ah thanks, script produced confusing output, 1s
