### ISSUE TITLE
The City Council voting chart for June 20, 2023 does not indicate that CM Eyer left before the last two votes.

### ISSUE THREAD

**Issue by kittybkahn** [a2council/a2council.vote#59]
CM Eyer left before the votes on items DC-7 and DC-8.  She just got up and left the meeting, so she should have been marked absent for those two votes, rather than Yes.  CM Eyer's absence for those two votes was in the meeting minutes.

**Comment by bdimcheff** [comment]
thanks for catching this, we just corrected it

**Comment by kittybkahn** [comment]
Thanks. -Peace, Kitty

On 8/7/23, 4:41 PM, "Brandon Dimcheff" ***@***.******@***.***>> wrote:


thanks for catching this, we just corrected it
